#!/usr/bin/env python3
"""Generate the reusable workflow contract reference directly from YAML."""
import pathlib
import sys
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
DESTINATION = ROOT / 'docs/reference.md'


def cell(value):
    return str(value).replace('|', '\\|').replace('\n', '<br>')


def render():
    lines = ['# Workflow reference', '', 'Generated by `python scripts/reference.py`. Edit workflow descriptions, then regenerate.', '']
    directory = ROOT / '.github/workflows'
    for path in sorted(set(directory.glob('*.yml')) | set(directory.glob('*.yaml'))):
        workflow = yaml.safe_load(path.read_text())
        triggers = workflow.get('on', workflow.get(True, {}))
        if 'workflow_call' not in triggers or path.name == 'contract-tests.yml':
            continue
        call = triggers['workflow_call'] or {}
        lines += ['## ' + path.name, '', workflow['name'] + '.', '', '| Input | Type | Required | Default | Description |', '| --- | --- | --- | --- | --- |']
        for name, spec in call.get('inputs', {}).items():
            lines.append('| ' + ' | '.join(cell(x) for x in [name, spec['type'], spec.get('required', False), spec.get('default', ''), spec.get('description', '')]) + ' |')
        for title, field in [('Secrets', 'secrets'), ('Outputs', 'outputs')]:
            lines += ['', '### ' + title, '']
            specs = call.get(field, {})
            if not specs:
                lines += ['None.']
            for name, spec in specs.items():
                lines += ['- `' + name + '`: ' + spec.get('description', '') + (' (required)' if spec.get('required') else '') + '.']
        lines += ['', '### Job permissions', '']
        for name, job in workflow['jobs'].items():
            permissions = job.get('permissions', workflow.get('permissions', {}))
            if isinstance(permissions, dict):
                description = ', '.join('`' + key + ': ' + value + '`' for key, value in permissions.items()) or '`{}` (no token permissions)'
            else:
                description = '`' + str(permissions) + '`'
            lines += ['- `' + name + '`: ' + description + '.']
        lines += ['']
    return '\n'.join(lines)


if __name__ == '__main__':
    output = render()
    if '--check' in sys.argv:
        if not DESTINATION.is_file() or DESTINATION.read_text() != output:
            raise SystemExit('Workflow reference is stale; run python scripts/reference.py')
    else:
        DESTINATION.parent.mkdir(exist_ok=True)
        DESTINATION.write_text(output)
